parameters:
    dynamic_search.console.logger.options:
        format: "[%%datetime%%] %%level_name%%: %%start_tag%%%%message%%%%end_tag%% %%extra%%\n"

services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DynamicSearchBundle\Logger\ProviderContextProcessor:
        tags:
            - { name: monolog.processor, handler: dynamic_search_stream_logging }

    DynamicSearchBundle\Logger\LoggerInterface: '@DynamicSearchBundle\Logger\Logger'
    DynamicSearchBundle\Logger\Logger:
        tags:
            - { name: monolog.logger, channel: dynamic_search }

    dynamic_search.log.formatter.stream.provider:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "[%%datetime%%] [%%extra.provider%%] [%%extra.contextName%%] %%level_name%%: %%message%%\n"

    dynamic_search.log.formatter.console.provider:
        class: Symfony\Bridge\Monolog\Formatter\ConsoleFormatter
        arguments:
            - '%dynamic_search.console.logger.options%'
