doctrine_migrations:
    migrations_paths:
        'DynamicSearchBundle\Migrations': '@DynamicSearchBundle/Migrations'

monolog:
    channels: ['dynamic_search']
    handlers:

        console:
            type: console
            channels:
                type: exclusive
                elements: ['!dynamic_search']

        dynamic_search_stream_logging:
            type: rotating_file
            max_files: 1
            path: '%kernel.logs_dir%/dynamic_search-%kernel.environment%.log"
            channels: ['dynamic_search']
            formatter: dynamic_search.log.formatter.stream.provider

        dynamic_search_console_logging:
            type: console
            verbosity_levels:
                VERBOSITY_NORMAL: DEBUG
                VERBOSITY_VERBOSE: DEBUG
                VERBOSITY_VERY_VERBOSE: DEBUG
                VERBOSITY_DEBUG: DEBUG
            channels: ['dynamic_search']
            formatter: dynamic_search.log.formatter.console.provider