imports:
    - { resource: services/*.yml }

services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DynamicSearchBundle\Service\LockServiceInterface: '@DynamicSearchBundle\Service\LockService'
    DynamicSearchBundle\Service\LockService: ~

    DynamicSearchBundle\Service\LongProcessServiceInterface: '@DynamicSearchBundle\Service\LongProcessService'
    DynamicSearchBundle\Service\LongProcessService: ~

    DynamicSearchBundle\Configuration\ConfigurationInterface: '@DynamicSearchBundle\Configuration\Configuration'
    DynamicSearchBundle\Configuration\Configuration: ~
